### Usando a GPU

Até o dado momento estávamos trabalhando com a criacao dos tensores utilizando a CPU (default). Agora iremos ver como é possível  trabalhar com tensores e suas operacoes utilizando a GPU.

Uma observacao a se fazer logo no ínicio é que, só iremos abordar as ténicas utilizadas com as GPUs da Nvidia, isso se deve ao fato da compatilidade com o Pytorch, entretanto é bem provável que existam estudos sobre APIs do Pytorch para GPUs AMD, por exemplo.

Vamos criar um vetor para entender como o Pytorch funciona nas GPUs e além disso iremos realizar algumas manipulacoes com estes tensores.

Um ponto interessante a se observar é que ao criarmos os tensores (ordem 1 até ordem n), todos eles sao armazenados na memória RAM, e ao realizarmos operacoes matemáticas entre eles estamos utilizando a CPU para fazer isso.

In [5]:
import torch

In [4]:
vector1 = torch.tensor([1,2,3])

vector2 = torch.tensor([5,8,1])


result = vector1 * vector2 

result

tensor([ 5, 16,  3])

### Utilizando o CUDA

O cuda nos permite fazer uma série de coisas, quando o assunto é GPU. Vamos exibir alguns exemplos abaixo:

In [15]:
tensor1_gpu = vector1.cuda()

Um dos primeiros conceitos e talvez um dos mais importantes que iremos tentar reproduzir aqui é que nao é possível multiplicar, somar, subtrair ou realizar operacoes matemáticas entre Tensores ao qual estes tensores estao em regioes de memória diferentes ou seja:

Tensor 1 está alocado na RAM do computador 
Tensor 2 está alocado na VRAM da GPU

Logo, se tentarmos realizar algum tipo de operacao matemática ela irá retornar um erro veja:

`Expected all tensor to be on the same device, but found at least two devices cuda:0 and cpu`

Ou seja ela fala o seguinte, você está tentando realizar uma operacao matemática com elementos(tensores) que estao em regioes de memória diferente e estao utilizando disposivos diferentes. Pois como abordado anteriormente, para realizarmos operacoes matemáticas por padrao utilizamos a CPU para fazer isso, porém na célula de código acima utilizamos o método `.cuda()` para mover o tensor `vector1` para a memória da GPU e portanto para executar a operacao matemática `vector1 * vector2` é preciso garantir que ambos os tensores sejam executados pelo mesmo dispositivo, ambos na CPU ou GPU e portanto eles precisam estar no mesmo "contexto".

In [16]:
tensor1_gpu * vector2

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [17]:
tensor2_gpu = vector2.cuda()

Veja que quando executamos entao agora as operacoes em tensores que estao no mesmo contexto ou melhor estao no mesmo dispositivo, nao recebemos nenhuma mensagem de erro tudo corre bem e ele retorna uma informacao: `device = 'cuda:0'` , isso nos indica que o tensor está guardado dentro da GPU

In [18]:
tensor1_gpu * tensor2_gpu

tensor([ 5, 16,  3], device='cuda:0')

### Criando tensores direto na GPU

Até agora, o que mostramos é que criamos vetores normalmente utilizando o módulo `tensor` do `Pytorch` e posteriormente nos apenas movemos eles de uma regiao de memória para outra regiao de memória ou melhor, movemos os tensores para regiao de memória de outro dispositivo sendo este a GPU, através do uso do CUDA

Agora, vamos mostrar como é possível criar os tensores diretamente na regiao de memória da GPU, ou seja, nao sendo necessário mais mover utilizando o CUDA

In [21]:
tensor3_gpu = torch.tensor([1,2,3] , device = 'cuda')

tensor3_gpu

tensor([1, 2, 3], device='cuda:0')

Logo, veja que agora, nao foi necessário mover nenhum tensor para a GPU, como era feito anteriormente pelo método `.cuda()` agora ao criar ele ja foi informado como argumento adicional dentro do método tensor:  

`device='cuda:0'`

### Verificando a disponiabilidade do CUDA, no ambiente e boas maneiras ao se trabalhar com o torch CUDA

É muito importante, que todas essas etapas, atendam a diferentes ambientes principalmente quando estamos propondo alguma arquitetura de rede neural ou algo do tipo, logo o código deve atender as particularidades do ambiente do usuário e para isso podemos checar se há GPU e torch CUDA disponível no ambiente:


In [24]:
if torch.cuda.is_available():
    device = 'cuda'
else:
    device = 'cpu'


new_gpu_tensor = torch.tensor([1,2,3,5], device = device)


new_gpu_tensor

tensor([1, 2, 3, 5], device='cuda:0')