### 💡 Criacao e inicializacao de Tensores

As operacoes de criacao de tensores no Pytorch sao ferramentas fundamentais, pois sao extremamente utilizadas em Machine Learning, Deep Learning
Data Science e em muitas outras áreas. Nestas áreas, existe uma grande necessidade de se trabalhar e manipular tensores e abaixo,
vamos ilustrar os métodos mais utilizados:

1.  **torch.zeros()**: Responsável por criar tensores 'n' dimensional preencchido com zeros, parecido com outros geradores como Numpy no Matlab e ou
outras linguagens

- **Caso de uso**: Este método é muito útil quando é necessário um tensor base para acumular valores, como em somas em um loop
ou por exemplo é extremamente utilizado ao se trabalhar com Backpropagation em redes MLP, para acumular valores ou para inicializar os pesos
de uma rede neural, embora seja uma partica menos utilizada.

Existem diversas maneiras de se utilizar o `torch.zeros`, para que o método seja funcional devemos informar para ele pelo menos **1 valor** ou também podemos dizer que é necessário passar ao menos um tensor de ordem 1, pois neste caso se este valor único for informado ele irá retornar um **vetor** ou **tensor** de ordem 1 com a quantidade de zeros preenchida correspondente a quantidade que foi informada no método.

In [12]:
import torch

vector = torch.zeros(4)

print(vector)
print(vector.shape)

tensor([0., 0., 0., 0.])
torch.Size([4])


É possível também criar tensores de ordem maior por exemplos tensores de ordem 2 e ordem 3 veja:

- Vamos inicialmente criar um tensor de ordem 2, para isso veja que iremos informar que queremos 2 linhas e 3 colunas. Logo, o método torch.zeros(2,3) irá retornar uma **matriz** (tensor ordem 2), contendo 2 linhas e 3 colunas. Portanto, é só informar a quantidade de elementos que se quer pela quantidade de dimensoes que se quer

In [14]:
matrice = torch.zeros(2,3, dtype=torch.uint32)
print(matrice)
print(matrice.shape)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.uint32)
torch.Size([2, 3])


Além disso, podemos também ter de maneira análoga ao feito para o tensor de ordem 2, é possível fazer para o tensor de ordem 3 e a única modificacao que é necessária de ser feita é adicionar uma dimensao.

In [4]:
tensor = torch.zeros(2,2,3)
print(tensor)
print(tensor.shape)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])


2.  **torch.ones()**: Responsável por criar um tensor 'n' dimensional preenchido com números **1**

- **Caso de uso**:  Muito utilizado para criar "mascaras", normalmente utilizado no contexto de redes neurais ao se trabalhar com **dropout** com objetivo de evitar ou **diminuir o overfit do modelo**. Mas como assim? o procedimento é simples como o método `torch.ones()` nos retorna vetores preenchidos com valores 1, entre estes valores 1 se adicionam valores zero e posteriormente se multiplica pelos valores da entrada da rede neural e ai entao tem-se uma espécie de máscara pois qualquer valor multiplicado por zero, sera 0.

In [5]:
ord1_tensor = torch.ones(4)
print(ord1_tensor)

tensor([1., 1., 1., 1.])


In [6]:
ord2_tensor = torch.ones(3,5)
print(ord2_tensor)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [7]:
ord3_tensor = torch.ones(3,3,3)
print(ord3_tensor)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


Logo, podemos notar que por mais que estejamos trabalhando com tensores de ordem 0,1,2,3 desde o ínicio do estudo de tensores isso nao significa que o módulo tensor seja limitado a isso. Como ja mencionado durante algumas observacoes e explanacoes, a inicializacao dos tensores pode ser de ordem o até ordem n, onde basta adaptar o número de dimensoes conforme for necessário.

3.  **torch.rand()**: Cria um tensor com valores aletórios com valores uniformemente distribuídos ou em outras palavras cria ou inicializa um tensor com valores aleatórios seguindo uma distribuicao uniforme
- **Caso de uso**: Este método é muito utilizado para inicializar os pesos de uma rede neural por exemplo, já que normalmente os pesos de uma rede neural sao inicializados com valores aleatórios que posteriormente serao optimizados através de alguma técnica de otimizacao como Stocastic Gradient Descent por exemplo. gera valores entre 0 e 1

In [22]:
random_tensor = torch.rand(4)
print(random_tensor)

tensor([0.4887, 0.7744, 0.1333, 0.4912])


In [9]:
rand_tensor1 = torch.rand(2,3)
print(rand_tensor1)

tensor([[0.2579, 0.8253, 0.2264],
        [0.3322, 0.0997, 0.7361]])


In [10]:
rand_tensor2 = torch.rand(2,3,6)
print(rand_tensor2)

tensor([[[0.8243, 0.5449, 0.3278, 0.4985, 0.2112, 0.6157],
         [0.0431, 0.5848, 0.0809, 0.1324, 0.6064, 0.2210],
         [0.2432, 0.0865, 0.9929, 0.1290, 0.7732, 0.8747]],

        [[0.5709, 0.8903, 0.0398, 0.6204, 0.4639, 0.6038],
         [0.2114, 0.3910, 0.7623, 0.7430, 0.4407, 0.9496],
         [0.4874, 0.6306, 0.2957, 0.8788, 0.6004, 0.7478]]])


4.  **torch.randn()**: Este método é muito parecido com o torch.rand, porém diferentemente ele cria um tensor com valores aleatórios porém seguindo uma distribuicao normal, ou também muito conhecida como distribuicao gaussiana

- **Caso de uso**: E de maneira análoga um dos principais caso de uso deste método e para realizar a inicializacao de pesos de uma rede neural, porém este método tem uma particularidade ele gera valores randomicos com valores entre -1 e 1. (Normal padronizada)  $(\alpha = 0 , \theta = 1)$

In [11]:
gaussian_tensor = torch.randn(10)
gaussian_tensor

tensor([ 2.4450,  0.1846,  1.5569, -0.8070,  0.8241, -0.8518, -2.6100, -1.0074,
        -1.4556, -0.9220])

In [12]:
gaussian_tensor2d = torch.randn(3,6)
gaussian_tensor2d

tensor([[ 0.6851,  1.7652,  0.1203,  1.9294,  0.9716,  0.4198],
        [ 0.4864, -1.0118, -0.1279,  0.1566, -1.4981,  0.5170],
        [-0.4545,  1.3726,  0.7099,  0.1283,  1.2079,  0.1762]])

In [23]:
gaussian_tensor3d = torch.randn(2,3,6)
gaussian_tensor3d

tensor([[[ 0.0791,  1.9714,  1.5102,  1.2269,  1.0618, -1.6533],
         [-1.7467, -0.4388, -0.9460, -2.9648, -0.0447,  0.7426],
         [-0.0795, -0.5235,  0.2265,  1.3435, -0.8059, -0.8603]],

        [[-0.2372, -0.1399, -2.5591,  0.4283,  2.1688, -0.1868],
         [ 0.1828,  0.3666, -2.7581, -0.6882,  1.4558,  1.3762],
         [-1.1815, -0.0949,  0.4675, -0.2590, -0.5231, -0.8510]]])

5.  **torch.arange()**: Este método cria um tensor com uma sequência de valores em um intrevalo específico informado como argumento. parecido com as generators functions do Python `range()`

- **Caso de uso**: É bastante utilizado quando se precisa de uma sequência númerica contínua. Um ponto importante a ser mencionado é que o método `arange()` só cria tensores de ordem 1 (vetores), nao sendo possível criar tensores de ordem superior

In [24]:
numbers = torch.arange(10)
numbers

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
numb_matrice = torch.arange(2,3,2)
numb_matrice

tensor([2])

6. **torch.full()**: Cria um tensor preenchido com valor especificado como argumento.

- **Caso de uso**: Este método é muito utilizado quando é necessário um tensor que contém um valor constante em todas as suas entradas. Isso pode ser útil em várias situacoes, como inicializacao de um tensor com um valor de bias por exemplo no contexto de redes neurais. Um coisa importante a ser mencionado é que o método `torch.full()` funciona um pouco diferente da seguinte maneira: é necessário informarmos uma `tupla()` contendo as dimensoes do tensor e também o valor que será preenchido veja abaixo:

In [26]:
one_d = torch.full((10,),0.5)
one_d

tensor([0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000,
        0.5000])

In [27]:
two_d = torch.full((3,6),2.5)
two_d

tensor([[2.5000, 2.5000, 2.5000, 2.5000, 2.5000, 2.5000],
        [2.5000, 2.5000, 2.5000, 2.5000, 2.5000, 2.5000],
        [2.5000, 2.5000, 2.5000, 2.5000, 2.5000, 2.5000]])

In [28]:
tree_d = torch.full((2,3,4),0.98)
tree_d

tensor([[[0.9800, 0.9800, 0.9800, 0.9800],
         [0.9800, 0.9800, 0.9800, 0.9800],
         [0.9800, 0.9800, 0.9800, 0.9800]],

        [[0.9800, 0.9800, 0.9800, 0.9800],
         [0.9800, 0.9800, 0.9800, 0.9800],
         [0.9800, 0.9800, 0.9800, 0.9800]]])

7. **torch.from_numpy()**: Este método é muito intuitivo pois ele faz literalmente o que seu nome exprime ou seja, este método cria ou permite inicializar um tensor a partir de um **array Numpy**
e como exibido abaixo é possível criar o tensor, através do numpy diretamente sem precisar de utilizar o método `from_numpy()` devido a compatibilidade do torch com o numpy e portanto, pode-se criar diretamente o tensor utilizando o módulo `torch.tensor()`

In [29]:
import numpy as np

x = np.array([1,2,3])

np_tensor = torch.from_numpy(x)
np_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [30]:
y = torch.tensor(x)
y

tensor([1, 2, 3], dtype=torch.int32)

Durante a explanacao mostrando os conceitos de inicializacao de tensores, foi possível aprender os seguintes métodos:
1. **torch.zeros()**
2. **torch.ones()**
3. **torch.rand()**
4. **torch.randn()**
5. **torch.arange()**
6. **torch.full()**
7. **torch.from_numpy()**

E sendo assim, uma observacao interessante a se fazer e que nao foi explanada durante este notebook é que todos métodos citados acima, cada um deles suportam o argumento: `dtype=torch.<type>`. Entretanto, mesmo que eles suportem o argumento dtype, isso nao quer dizer que todos aceitam os mesmos dytpes, pois existem algumas consideracoes a se fazer.

- **Tipos de dados suportados pelo dtype**
    - **torch.int8** , **torch.int16** , **torch.int32** , **torch.int64**
    - **torch.uint8** , **torch.uint16** , **torch.uint32** , **torch.uint64**
    - **torch.float16** , **torch.float32** , **torch.float64**
    
**OBS**: Entretanto, como observacao o método **torch.from_numpy()** nao aceita nenhum `dtype` e métodos como **torch.rand()** nao aceita nenhuma estrutura de dados **float**, justamente por sua caracteristica de gerar números aleatórios entre 0 e 1, a mesma coisa acontece para o **torch.randn()** pois gera números entre -1 e 1.