In [2]:
import torch

In [3]:
escalar = torch.tensor(6)
print(type(escalar))

<class 'torch.Tensor'>


C:\Users\Joao\AppData\Local\Temp\ipykernel_19928\3055716407.py:1: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  escalar = torch.tensor(6)


#### Veja que o método shape retorna um array vazio, ou seja a dimensao é zero.

Isso significa que o escalar é um tensor de ordem 0. (0 dimensoes)

In [4]:
escalar.shape 

torch.Size([])

É possível realizar operacoes matemáticas normalmente por exemplo: Adicao, subtracao , Multiplicacao, Divisao e etc.

In [5]:
escalar / 2

tensor(3.)

É possível também realizar operacoes de entre escalares, como por exemplo multiplicacao de 2 escalares

In [6]:
escalar2 = torch.tensor(4)

result = escalar * escalar2

result

tensor(24)

### Vetores

In [8]:
vector = torch.tensor([4 , 5 , 6, 7])

vector

tensor([4, 5, 6, 7])

Veja que aqui de maneira análoga aos escalares verificamos que o vetor é um tensor de ordem 1, ou seja, possui uma dimensao.

In [9]:
vector.shape

torch.Size([4])

Aqui temos a divisao de um tensor de ordem 1, por um número por exemplo

In [10]:
vector / 2 

tensor([2.0000, 2.5000, 3.0000, 3.5000])

Como visto para os escalares as mesmas propriedades valem para os vetores, por exemplo podemos realizar operacoes matemáticas entre tensores, por exemplo:

In [11]:
vector2 = torch.tensor([4,5,7,8])

result = vector2 / vector

result

tensor([1.0000, 1.0000, 1.1667, 1.1429])

### Matrizes



In [13]:
matrix = torch.tensor([[1,2,3],[4,5,6]])

In [15]:
matrix.shape

torch.Size([2, 3])

Veja que novamente, todas as propriedades e métodos utilizados tanto por escalares quanto pelos vetores, também podem ser utilizados e aplicados para se trabalhar com matrizes.

Em termos práticos, podemos dizer que as matrizes, sao vetores que carregam vetores. Vamos, mostrar que as mesmas propriedades matemáticas se aplicam.


**Um ponto importante a salientar que as operacoes entre tensores irá retornar sempre a dimensao do tensor mais a esquerda independente de sua ordem**

In [16]:
matrix / 4

tensor([[0.2500, 0.5000, 0.7500],
        [1.0000, 1.2500, 1.5000]])

In [17]:
matrix2 = torch.tensor([[4,2,4],[5,6,8]])

In [19]:
result_m = matrix * matrix2
result_m

tensor([[ 4,  4, 12],
        [20, 30, 48]])

### Tensores

**Tensores de ordem 3** carregam 3 dimensoes, e sao ideias para se trabalhar com imagens, pois eles possuem 3 dimensoes assim como as imagens ou seja, eles carregam as posicoes x e y e informacoes do pixeis dos canais de cores totalizando 3 dimensoes

Em termos práticos podemos dizer que assim como as matrizes sao elementos que carregam um conjunto de vetores, podemos afirmar que os Tensores sao elementos que carregam **uma matriz de matrizes ou melhor carrega um conjunto de matrizes**

In [21]:
tensor = torch.tensor([[[3,5,6],[7,8,8]]])

tensor

tensor([[[3, 5, 6],
         [7, 8, 8]]])

In [22]:
tensor.shape

torch.Size([1, 2, 3])

Veja que o resultado acima retornou um shape do tipo ([1,2,3]) ou seja está nos falando que ele é um vetor que carrega uma matriz 2x3 (2 linhas e 3 colunas). Logo, podemos afirmar que ele de fato é um Tensor de ordem 3.

Além disso, um outro detalhe que é possível afirmar é que, perfeito o Tensor é de ordem 3. Sendo assim, todas as propriedades matematicas feitas para os Escalares,Vetore e Matrizes, também valem para o tensor 

In [24]:
tensor + 1

tensor([[[4, 6, 7],
         [8, 9, 9]]])

Um ponto muito importante a ser observado e que a primeiro momento, por alguém mais despercebido, nao é necessário ao se trabalhar com o método `tensor()` fazer loops for para varrer cada elemento da lista para aplicar as operacoes matemáticas o método tensor ja realiza este cálculo automaticamente o que aumenta muito a produtividade e facilita muito o trabalho do profissional que trabalha com Visao Computacional por exemplo.

In [25]:
tensor2 = torch.tensor([[[2,3,5],[5,9,0]]])

In [26]:
t_result = tensor2 - tensor

t_result

tensor([[[-1, -2, -1],
         [-2,  1, -8]]])