### 📡 Broadcasting

Broadcasting é um mecanismo que permite realizar operações aritméticas entre tensores de diferentes formas (ou tamanhos):

1. **Como foi possível observar até agora, cada tensor possui pelo menos uma dimensão.**
- Isso significa que os tensores envolvidos na operação devem ter pelo menos uma dimensão. Um tensor não pode ser um escalar (um único número sem dimensões) se quisermos aplicar as regras de broadcasting.

2. **O Broadcasting** é algo que acontece tanto no **Pytorch** quanto no **Numpy** porém é algo ocorrendo debaixo dos panos nao é nenhum método que será aplicado ao tensor por exemplo. Entretanto, o broadcasting possui alguns príncipios de funcionamento, e compreender isto, auxília ao desenvolvedor ter um maior domínio do que está acontecendo com seus tensores.

 Para que o broadcasting entao aconteca esta operacao irá sempre comecar verificando se a dimensão final possui os tamanhos das compativéis que permitem o broadcasting sendo rem resumo:
 
   - As dimensoes mais a direita devem ser iguais;
   - Algum dos valores ou dimensao é 1, ou um deles não existe;
  
  Como mencionado, o brodcasting inicia:
   - Comparando as dimensões dos dois tensores, começando pela última dimensão (a mais à direita) e movendo-se para a primeira dimensão (a mais à esquerda).
   
  Agora de maneira detalhada como já foi citado anteriormente para cada par de dimensões comparadas, três cenários permitem o broadcasting:
     1. **Os tamanhos das dimensões são iguais:** Se as dimensões correspondentes nos dois tensores têm o mesmo tamanho, então elas são compatíveis. (ocorre broadcasting)
     2. **Uma das dimensões é 1:** Se um tensor tem uma dimensão de tamanho 1 na posição que está sendo comparada, ele pode ser "esticado" ou "expandido" para corresponder ao tamanho da outra dimensão. Isso é feito sem realmente copiar dados em memória, mas sim apenas adaptando a operação aritmética para se comportar como se o tensor menor tivesse sido expandido.
     3. **Uma das dimensões não existe:** Se um dos tensores tem menos dimensões que o outro, podemos considerar que ele tem dimensões extras de tamanho 1 na frente (mais à esquerda). Essas dimensões "faltantes" são implicitamente consideradas como 1, permitindo o broadcasting.

![](https://deeplearninguniversity.com/wp-content/uploads/2020/11/Screenshot-2020-11-20-at-1.02.50-PM.png)

(Fonte: https://deeplearninguniversity.com/pytorch/pytorch-broadcasting/)

O broadcasting permite que você realize operações aritméticas entre tensores de formas diferentes de uma maneira eficiente e intuitiva. Por exemplo, você pode adicionar um vetor a cada linha de uma matriz ou multiplicar uma matriz 3D por um vetor, aplicando a operação em cada "fatia" da matriz 3D, sem a necessidade de loops explícitos ou duplicação de dados.

Vamos, observar alguns exemplos para que fique ainda mais claro, e também para podermos entender como o broadcasting ocorre na prática

In [1]:
import torch

n = torch.rand(2,2)

n

tensor([[0.8484, 0.3655],
        [0.6376, 0.4929]])

In [2]:
j = torch.rand(2)

j

tensor([0.6048, 0.5671])

Perceba que aqui as regras, para a existencia do **Broadcasting** estao sendo satisfeitas, pois, temos que a dimensao mais a direita é `1` ou uma dimensao maior, e neste caso se percebermos ambos os tensores possuem o mesmo número de colunas (dimensao mais a direita) ambos possuem 2 colunas (dimensoes iguais), portanto o **Tensor j** sofrerá **Broadcasting** e terá seus valores duplicados de tal forma que tenhamos uma matriz (2 x 2)

In [3]:
broad = n + j

broad

tensor([[1.4532, 0.9326],
        [1.2424, 1.0600]])

Um outro comentario interessante a se fazer em relacao ao Broadcasting é que ele é aplicado a todas as operacoes aritiméticas que vimos até aqui, incluindo por exemplo produtos escalares entre Tensores, sem nos esquecermos das operacoes aritémticas entre **Tensores** fundamentais como por exemplo (+, - , * , /) e etc.

O que devemos salientar é para os produtos escalares que no final das contas, a grosso modo sao modelos simplificados de um neuronio artificial e portanto, ao lidar com Redes MLP, ou Redes Convolucionais, estamos a todo momento trabalhando com o Broadcasting. Vamos ver um exemplo para consildar este conhecimento tao importante:

In [13]:
x = torch.rand(2,2,3)
w = torch.rand(3,2)
b = torch.rand(2)

In [15]:
neuron = torch.matmul(x, w) + b

neuron

tensor([[[1.6143, 1.1010],
         [1.2022, 1.0477]],

        [[1.0583, 1.0030],
         [2.0519, 1.3876]]])

In [16]:
neuron.shape

torch.Size([2, 2, 2])