### Acessando elementos pelo indice em Tensores

In [1]:
import torch
vector = torch.tensor([1,2,3,4,5,6])

C:\Users\Joao\AppData\Local\Temp\ipykernel_15712\109296347.py:2: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  vector = torch.tensor([1,2,3,4,5,6])


In [2]:
vector.shape

torch.Size([6])

In [3]:
vector[5]

tensor(6)

In [4]:
matrice = torch.tensor([[1,2,3],[4,5,6]])

matrice

tensor([[1, 2, 3],
        [4, 5, 6]])

In [5]:
matrice.shape

torch.Size([2, 3])

In [6]:
matrice[0]

tensor([1, 2, 3])

In [7]:
matrice[0][2]

tensor(3)

### Realizando slicing em Tensores de ordem 2 para acessar os indices

In [8]:
matrice

tensor([[1, 2, 3],
        [4, 5, 6]])

O slicing é uma maneira de fatiar filtrar ou até mesmo pode ser interpretado como uma maneira de buscar elementos em container ou melhor em colecoes como é chamado no Python.

Ao se trabalhar com Tensores esta técnica e extremamente utilizada e portanto é de extrema importância ter um bom dôminio desta ferramenta

Quando trabalhamos com Tensores de ordem 2 ou superior utilizamos a seguinte notacao: $$[:,:]$$ 

- os primeiros dois pontos percorrem ou melhor buscam tudo referente a linhas
- os últimos dois pontos sao responsaveis por percorrer tudo referente as colunas


In [9]:
matrice[1:,2:]

tensor([[6]])

###  Tensores de ordem 3

Ao se trabalhar com tensores de ordem 3, temos tudo com uma dimensao a mais como vimos nos primeiros tutorias os tensores podem ser de ordem 0 até ordem n.

Logo, como comentamos na prática os tensores de ordem 3 por exemplo em termos práticos ele é como se fosse um vetor ou melhor um tensor de ordem 1 que carrega matrizes ou seja tensores de ordem 2 e assim sucessivamente. 

Logo, em termos práticos os tensores serao uma estrutura n-2 que carrega em si um conjunto de estruturas n-1, onde n é a ordem do Tensor

Portanto, como os tensores seguem essa "hierarquia" ou melhor estrutura, eles também recebem as propriedades e seguem a mesma maneira de manipulacao de suas estruturas, e sendo assim o tensores de ordem 3 também respeitam as mesmas propriedades de "varredura" e slicing dos tensores de ordem 1 e 2 porém com uma dimensao a mais:

In [10]:
tensor = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [11]:
tensor

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [12]:
tensor.shape

torch.Size([2, 2, 3])

In [13]:
tensor[0][1][0]

tensor(4)

In [14]:
tensor[:,:,:]

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])